// Generated by CoffeeScript 1.9.1
(function() {
  section(function() {
    background('black');
    color('red');
    p(function() {
      font_size('12px');
      border_radius('5px');
      return color('green');
    });
    comment('and this is ' + title + ' comment');
    return table(function() {
      return border((px(3)) + 'solid red');
    });
  });

}).call(this);
