# ---------------
# Global Settings
# ---------------
vars:
  # Font stacks (add your own!)
  arial:            'Arial, sans-serif'
  helvetica-neue:   '"Helvetica Neue", HelveticaNeue, Helvetica, Arial, sans-serif'
  helvetica:        '"Helvetica Neue", Helvetica, Arial, sans-serif'
  georgia:          'Georgia, Cambria, "Times New Roman", Times, serif'
  lucidia-grande:   '"Lucida Grande", Tahoma, Verdana, Arial, sans-serif'
  verdana:          'Verdana, Geneva, sans-serif'



  # Default font settings
  font-stack:  verdana
  font-size:   16
  font-color:  '#555'

  # Colors (via http://clrs.cc - slightly modded)
  navy:      '#001F3F'
  blue:      '#0074D9'
  aqua:      '#7FDBFF'
  teal:      '#39CCCC'
  olive:     '#3D9970'
  green:     '#2ECC40'
  lime:      '#01FF70'
  yellow:    '#FFDC00'
  orange:    '#FF851B'
  red:       '#D13F19'
  maroon:    '#85144B'
  fuchsia:   '#F012BE'
  purple:    '#B10DC9'
  white:     '#FFFFFF'
  silver:    '#DDDDDD'
  gray:      '#AAAAAA'
  black:     '#222222'

  # Default color
  default-color: blue
  red-theme: red

  # Text highlight color
  highlight-color: teal

  # Custom image base path for roots mixins
  img-path: 'sasa'

  # Support for old IE this.bata
  support-for-ie: false

  # Ligatures
  ligatures: false

  # Vertical rhythm
  base-line-height: 24px
  default-rhythm-border-style: solid
  relative-font-sizing: true
  round-to-nearest-half-line: false
  min-line-padding: 2px